Repository webgriffe/SyliusActiveCampaignPlugin, pull requests merged in 2022-03, with the labels that each got.

#25 Propose order URL adr
  adr/2022_03_30_ecommerce_order_url.md
Labels: documentation

#32 Dispatch event for contact field values (#29)
  docs/03-Usage.md
  spec/Mapper/ContactMapperSpec.php
  src/Mapper/ContactMapper.php
  src/Resources/config/services/mapper.xml
Labels: enhancement

#33 Handle exceptions threw by enqueuers (#28)
  src/EventSubscriber/ChannelSubscriber.php
  src/EventSubscriber/CheckoutSubscriber.php
  src/EventSubscriber/CustomerSubscriber.php
  src/EventSubscriber/OrderSubscriber.php
  src/Resources/config/services.xml
  src/Resources/config/services/event_subscriber.xml
  src/Resources/config/services/logger.xml
  tests/DataFixtures/ORM/resources/EventSubscriber/CheckoutSubscriberTest/channels.yaml
  tests/DataFixtures/ORM/resources/EventSubscriber/CheckoutSubscriberTest/customers.yaml
  tests/DataFixtures/ORM/resources/EventSubscriber/CheckoutSubscriberTest/orders.yaml
  tests/Integration/EventSubscriber/CheckoutSubscriberTest.php
  tests/Integration/EventSubscriber/OrderSubscriberTest.php
Labels: bug, enhancement
